### ISSUE TITLE
cmake文件110，111行的移除skynet_main.c路径是否有误

### ISSUE THREAD

**Issue by 691407323** [hanxi/skynet-cmake#1]
aux_source_directory(skynet/skynet-src LIB_SKYNET_SRC)
      list(REMOVE_ITEM LIB_SKYNET_SRC skynet/lualib-src/skynet_main.c)
=》list(REMOVE_ITEM LIB_SKYNET_SRC skynet/skynet-src/skynet_main.c)

**Comment by hanxi** [comment]
可以提个pr吗？
