### ISSUE TITLE
cmake gui 生成不了

### ISSUE THREAD

**Issue by baidwwy** [hanxi/skynet-cmake#6]
卡在pthread

**Comment by hanxi** [comment]
我只试过直接用vs打开

**Comment by hanxi** [comment]
执行 git submodule update --init 了吗？

**Comment by baidwwy** [comment]
> 执行 git submodule update --init 了吗？

有的，显示是一个rc资源错误，好像是arch找不到平台

**Comment by hanxi** [comment]
你自己调试一下？我现在没环境。

**Comment by hanxi** [comment]
有没有具体的报错日志？

**Comment by baidwwy** [comment]
> 有没有具体的报错日志？
https://github.com/GerHobbelt/pthread-win32/blob/2c686a629d40781a54cdabb25db02f8428820622/CMakeLists.txt#L15-L29
```
The value of CMAKE_BINARY_DIR is: D:/skynet-cmake/cmake
CMake Error at 3rd/pthread-win32/CMakeLists.txt:29 (message):
  "unknown" not supported in version.rc


Configuring incomplete, errors occurred!
```

**Comment by baidwwy** [comment]
> 你自己调试一下？我现在没环境。

测试pthread可以用GUI生成，我不会CMAKE。。。

**Comment by hanxi** [comment]
我也不会呀，你直接用vs能跑不？

**Comment by baidwwy** [comment]
可以

**Comment by cloudfreexiao** [comment]
加了个 windows 的编译脚本 能够生产 sln 文件
https://github.com/cloudfreexiao/pluto/blob/main/build.bat#L1-L10

**Comment by baidwwy** [comment]
提示缺少ClangCL，安装后编译通过
